export const CRESTS_AND_SPECS = {
  1: ['armswarrior', 'furywarrior', 'protectionwarrior'],
  2: ['holypaladin', 'protectionpaladin', 'retributionpaladin'],
  3: ['beastmasteryhunter', 'marksmanshiphunter', 'survivalhunter'],
  4: ['assassinationrogue', 'outlawrogue', 'subtletyrogue'],
  5: ['disciplinepriest', 'holypriest', 'shadowpriest'],
  6: ['blooddeathknight', 'frostdeathknight', 'unholydeathknight'],
  7: ['elementalshaman', 'enhancementshaman', 'restorationshaman'],
  8: ['arcanemage', 'firemage', 'frostmage'],
  9: ['afflictionwarlock', 'demonologywarlock', 'destructionwarlock'],
  10: ['brewmastermonk', 'windwalkermonk', 'mistweavermonk'],
  11: ['balancedruid', 'feraldruid', 'guardiandruid', 'restorationdruid'],
  12: ['havocdemonhunter', 'vengeancedemonhunter'],
  13: ['devastationevoker', 'preservationevoker', 'augmentationevoker'],
};

export const CLASS_AND_SPECS = {
  "Warrior": ['Arms', 'Fury', 'Protection'],
  "Paladin": ['Holy', 'Protection', 'Retribution'],
  "Hunter": ['Beast Mastery', 'Marksmanship', 'Survival'],
  "Rogue": ['Assassination', 'Outlaw', 'Subtlety'],
  "Priest": ['Discipline', 'Holy', 'Shadow'],
  "Death Knight": ['Blood', 'Frost', 'Unholy'],
  "Shaman": ['Elemental', 'Enhancement', 'Restoration'],
  "Mage": ['Arcane', 'Fire', 'Frost'],
  "Warlock": ['Affliction', 'Demonology', 'Destruction'],
  "Monk": ['Brewmaster', 'Windwalker', 'Mistweaver'],
  "Druid": ['Balance', 'Feral', 'Guardian', 'Restoration'],
  "Demon Hunter": ['Havoc', 'Vengeance'],
  "Evoker": ['Devastation', 'Preservation'],
}