export enum FRACTION {
  ALLIANCE = 'ALLIANCE',
  HORDE = 'HORDE',
}

export enum WOW_CLASS {
  'WARRIOR' = 'WARRIOR',
  'PALADIN' = 'PALADIN',
  'HUNTER' = 'HUNTER',
  'ROGUE' = 'ROGUE',
  'PRIEST' = 'PRIEST',
  'DEATH KNIGHT' = 'DEATH KNIGHT',
  'SHAMAN' = 'SHAMAN',
  'MAGE' = 'MAGE',
  'WARLOCK' = 'WARLOCK',
  'MONK' = 'MONK',
  'DRUID' = 'DRUID',
  'DEMON HUNTER' = 'DEMON HUNTER',
  'EVOKER' = 'EVOKER',
}

export enum WOW_SPEC {
  'armswarrior' = 'armswarrior',
  'furywarrior' = 'furywarrior',
  'protectionwarrior' = 'protectionwarrior',
  'holypaladin' = 'holypaladin',
  'protectionpaladin' = 'protectionpaladin',
  'retributionpaladin' = 'retributionpaladin',
  'beastmasteryhunter' = 'beastmasteryhunter',
  'marksmanshiphunter' = 'marksmanshiphunter',
  'survivalhunter' = 'survivalhunter',
  'assassinationrogue' = 'assassinationrogue',
  'outlawrogue' = 'outlawrogue',
  'subtletyrogue' = 'subtletyrogue',
  'disciplinepriest' = 'disciplinepriest',
  'holypriest' = 'holypriest',
  'shadowpriest' = 'shadowpriest',
  'blooddeathknight' = 'blooddeathknight',
  'frostdeathknight' = 'frostdeathknight',
  'unholydeathknight' = 'unholydeathknight',
  'elementalshaman' = 'elementalshaman',
  'enhancementshaman' = 'enhancementshaman',
  'restorationshaman' = 'restorationshaman',
  'arcanemage' = 'arcanemage',
  'firemage' = 'firemage',
  'frostmage' = 'frostmage',
  'afflictionwarlock' = 'afflictionwarlock',
  'demonologywarlock' = 'demonologywarlock',
  'destructionwarlock' = 'destructionwarlock',
  'brewmastermonk' = 'brewmastermonk',
  'windwalkermonk' = 'windwalkermonk',
  'mistweavermonk' = 'mistweavermonk',
  'balancedruid' = 'balancedruid',
  'feraldruid' = 'feraldruid',
  'guardiandruid' = 'guardiandruid',
  'restorationdruid' = 'restorationdruid',
  'havocdemonhunter' = 'havocdemonhunter',
  'vengeancedemonhunter' = 'vengeancedemonhunter',
  'devastationevoker' = 'devastationevoker',
  'preservationevoker' = 'preservationevoker',
  'augmentationevoker' = 'augmentationevoker',
}

export enum WOW_RACE {
  fbloodelf = 'fbloodelf',
  fdarkirondwarf = 'fdarkirondwarf',
  fdracthyr = 'fdracthyr',
  fdraenei = 'fdraenei',
  fdwarf = 'fdwarf',
  fgnome = 'fgnome',
  fgoblin = 'fgoblin',
  fhighmountain = 'fhighmountain',
  fhuman = 'fhuman',
  fkultiran = 'fkultiran',
  flightforged = 'flightforged',
  fmagharorc = 'fmagharorc',
  fmechagnome = 'fmechagnome',
  fnightborne = 'fnightborne',
  fnightelf = 'fnightelf',
  forc = 'forc',
  fpandaren = 'fpandaren',
  ftauren = 'ftauren',
  ftroll = 'ftroll',
  fundead = 'fundead',
  fvoidelf = 'fvoidelf',
  fvulpera = 'fvulpera',
  fworgen = 'fworgen',
  mbloodelf = 'mbloodelf',
  mdarkirondwarf = 'mdarkirondwarf',
  mdracthyr = 'mdracthyr',
  mdraenei = 'mdraenei',
  mdwarf = 'mdwarf',
  mgnome = 'mgnome',
  mgoblin = 'mgoblin',
  mhighmountain = 'mhighmountain',
  mhuman = 'mhuman',
  mkultiran = 'mkultiran',
  mlightforged = 'mlightforged',
  mmagharorc = 'mmagharorc',
  mmechagnome = 'mmechagnome',
  mnightborne = 'mnightborne',
  mnightelf = 'mnightelf',
  morc = 'morc',
  mpandaren = 'mpandaren',
  mtauren = 'mtauren',
  mtroll = 'mtroll',
  mundead = 'mundead',
  mvoidelf = 'mvoidelf',
  mvulpera = 'mvulpera',
  mworgen = 'mworgen',
}

export enum WOW_CLASS_ICON {
  WARRIOR = 'WARRIOR',
  PALADIN = 'PALADIN',
  HUNTER = 'HUNTER',
  ROGUE = 'ROGUE',
  PRIEST = 'PRIEST',
  DEATHKNIGHT = 'DEATHKNIGHT',
  SHAMAN = 'SHAMAN',
  MAGE = 'MAGE',
  WARLOCK = 'WARLOCK',
  MONK = 'MONK',
  DRUID = 'DRUID',
  DEMON_HUNTER = 'DEMONHUNTER',
  EVOKER = 'EVOKER',
}
